%YAML:1.0

#Image Resolution and Scale Factor
Width: 640
Height: 480

#Camera Intrinsics and Extrinsic with respect to imu
Cam0_model: PINHOLE

#fx, fy, cx, cy
Cam0_k: [259.5175, 259.8282, 316.7504, 234.4396]
#k1, k2, p1, p2
Cam0_d: [-0.0175, 0.0295, -6.8161e-4, 1.9262e-4]
